"""empty message

Revision ID: 41925d36fda0
Revises: 8e661e5e2235
Create Date: 2022-06-07 11:40:37.548980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41925d36fda0'
down_revision = '8e661e5e2235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
