"""empty message

Revision ID: 791365d35932
Revises: e0ef9cd5bbab
Create Date: 2022-05-25 14:04:15.514268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791365d35932'
down_revision = 'e0ef9cd5bbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
